### ISSUE TITLE
Add test cases to the project

### ISSUE THREAD

**Issue by hungtcs** [typed-mxgraph/typed-mxgraph#21]
I have planned to add test cases, based on [jest]. The basic work is now complete in [new branch](https://github.com/typed-mxgraph/typed-mxgraph-demo/tree/test-case) and has been tested in [typed-mxgraph-demo](https://github.com/typed-mxgraph/typed-mxgraph-demo), a simple project. At the same time I modified the project structure in order to distinguish between tests and source. Because of a lot of changes, I can't merge to the master branch hastily, @tbouffard please help me to review.
 
[jest]: https://jestjs.io

**Comment by tbouffard** [comment]
Ok I have to setup a test project, I keep you posted

**Comment by hungtcs** [comment]
Thank you @tbouffard
