### ISSUE TITLE
mxUtils.bind throws TS2345 when using sort

### ISSUE THREAD

**Issue by l33the** [typed-mxgraph/typed-mxgraph#27]
Im trying to write a Layout based on mxStackLayout so i wrote the class in typescript completely. While doing this, this error occured:

```
ERROR in [at-loader] ./target/flow-frontend/ts/mxGraph/SnakeLayout.ts:197:24 
    TS2345: Argument of type 'Function' is not assignable to parameter of type '(a: any, b: any) => number'.
  Type 'Function' provides no match for the signature '(a: any, b: any): number'.

```
The code that causes this is:

```
     let instance = this;
     cells.sort(mx.mxUtils.bind(this, (c1: mxCell, c2: mxCell):number =>  {
                let geo1 = (instance as mxGraphLayout).graph.getCellGeometry(c1);
                let geo2 = (instance as mxGraphLayout).graph.getCellGeometry(c2);

                return (instance.horizontal) ?
                    ((geo1.x == geo2.x) ? 0 : ((geo1.x > geo2.x && geo2.x > 0) ? 1 : -1)) :
                    ((geo1.y == geo2.y) ? 0 : ((geo1.y > geo2.y && geo2.y > 0) ? 1 : -1));
            }));
```

Without using mxUtils.bind, it works.

I guess since this method is kinda obsolete anyway for me, its not a big deal, but i think somethings wrong with that Function parameter in mxUtils.bind.

Best regards,

Sebastian Göhring

**Comment by hungtcs** [comment]
Hi @TheSilentHorizon, thanks for your report, it looks like you are using arrow function expressions, so `mxUtils.bind` is redundant here. The cause of the problem is `mxUtils.bind` return a Function type and do not match `(a: any, b: any) => number`. I will try to use generics to solve this problem, but it is not guaranteed to be effective.

**Comment by hungtcs** [comment]
Test case passed: https://github.com/typed-mxgraph/typed-mxgraph/blob/master/tests/util/mxUtils.spec.ts
