### ISSUE TITLE
Wrong type of "createSelectionCellsHandler" method in mxGraph

### ISSUE THREAD

**Issue by usvintsitski** [typed-mxgraph/typed-mxgraph#33]
Currently it has [type of "mxSelectionCellHandler"](https://github.com/typed-mxgraph/typed-mxgraph/blob/master/lib/view/mxGraph.d.ts#L882) instead of a function which returns an instance of "mxSelectionCellHandler".

**Comment by tbouffard** [comment]
Confirmed, see https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/src/js/view/mxGraph.js#L1744
@vvsvintsitsky could you create a Pull Request to fix this problem?

**Comment by hungtcs** [comment]
Hi @tbouffard, fixed in new version [v1.0.1](https://www.npmjs.com/package/@typed-mxgraph/typed-mxgraph/v/1.0.1). And previous two pr.

**Comment by tbouffard** [comment]
Thx @hungtcs for the PR merges and the new `1.0.1` release
