### ISSUE TITLE
Request of "Usage Addition"

### ISSUE THREAD

**Issue by byungksy** [typed-mxgraph/typed-mxgraph#4]
Hello, I want to report the trouble-shooting case by me.

At the first, Usage was followed properly,
![ThisUsage](https://i.imgur.com/FyLgLt4.png)

but I get the ``TS7016`` Error In Vue-cli Project.

![TypeError](https://i.imgur.com/8OJ06JC.png)

In this situation, I added ``paths`` property in ``tsconfig.json`` and this is working.
Maybe we need to add the ``paths`` property for ``"mxgraph"`` type-mapping.

```
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@typed-mxgraph"
    ],
   ....
    "paths": {
      "@/*": [
        "src/*"
      ],
      "mxgraph": ["./node_modules/@typed-mxgraph/typed-mxgraph"]
    }
```

Please check!
Thank you!

**Comment by hungtcs** [comment]
Hi @byungster,  I tested it after seeing your proposal, but the problem did not recur. This is [my test case](https://github.com/typed-mxgraph/typed-mxgraph-demo) , it is a minimize application without any frameworks and build via webpack, I am using VSCode 1.48.2, I am not sure if this is related to the editor or the framework.
Can you provide an example that can reproduce the problem? Thank you!

**Comment by tbouffard** [comment]
Hi
I used the https://github.com/typed-mxgraph/typed-mxgraph-demo and other private projects (Vanilla TypeScript) and don't have the issue described here

**Comment by hungtcs** [comment]
This configuration may be suitable for some specific environments, but it is not universal, I will close this issues.
