### ISSUE TITLE
Let other contributors publish the npm package

### ISSUE THREAD

**Issue by tbouffard** [typed-mxgraph/typed-mxgraph#55]
Hi,
Today, the npm package is published at

- https://github.com/typed-mxgraph/typed-mxgraph/pkgs/npm/typed-mxgraph
- https://www.npmjs.com/package/@typed-mxgraph/typed-mxgraph

This is always done by @hungtcs (the repository owner) and other contributors have no way to publish the package (for instance, myself 😸).
The publication procedure is not public, so even if contributors get permission to publish the package, they'll need to understand all the steps involved in managing it. For instance, the GitHub release notes creation is part of the process: https://github.com/typed-mxgraph/typed-mxgraph/releases
This depends on the @hungtcs bandwidth which can delay the public availability of the package. Notice that @hungtcs has always been very reactive to publishing requests in the past, so it is not a criticism of the current situation. 

### Proposal

So I suggest introducing a GitHub workflow to publish the package and help produce the release notes.
It will allow
- self service for contributors
- fully automated procedure so no risk of error and self documented
- reduce pressure on the repository owner

If we agree on that, I can propose technical solutions and/or Pull Requests.

### Potential other benefits

Using a GitHub workflow will let us add the provenance of the package: https://github.blog/changelog/2023-04-19-npm-provenance-public-beta/

**Comment by hungtcs** [comment]
Thanks, @tbouffard . 
I completely agree with your viewpoint, our thoughts are in sync. To be honest, I'm currently preparing to add an automated publishing workflow later today. I'm currently testing it in another repository.

**Comment by tbouffard** [comment]
Perfect, thanks.
Please let me know if you need me to review and/or test it.

**Comment by tbouffard** [comment]
Implemented with #56
