### ISSUE TITLE
[Question] How to use Layouts for graph in cells?

### ISSUE THREAD

**Issue by tn4799** [typed-mxgraph/typed-mxgraph#58]
Hello. 
I'm working on a project of my university. There we need to build a subgraph inside of a cell. To prevent overlapping we want to use a layout, which isn't executed in the Screenshot. 
![image](https://github.com/typed-mxgraph/typed-mxgraph/assets/52242395/c37f9300-4655-4938-bf48-9a84ce063147)

My idea to make it possible was the creation of a graph inside the cell, so that the Step is always a part of the State. I've found the compositie layout to use multiple layouts, but didn't find any examples on how to use it. Has somebody maybe any tips or examples how I can achieve the goal?

Greetings
tn4799

**Comment by tbouffard** [comment]
Hi @tn4799 
Your question relates to the mxGraph usage, not to the usage of the mxGraph types.
So this is not the right place to ask such a question.

If you don't know where to ask, ask at https://github.com/maxGraph/maxGraph/discussions/categories/q-a

**Comment by tn4799** [comment]
Sorry for posting at the wrong location. I already thought this isn't the right place, but i didn't know where a better place is. I will post the question at the link you posted. Thanks.
