### ISSUE TITLE
Add the 'scrollTileSize' property to the 'mxGraph' class

### ISSUE THREAD

**Issue by EfrenHerrera** [typed-mxgraph/typed-mxgraph#59]
/**
     * Specifies the size of the size for "tiles" to be used for a graph with
     * scrollbars but no visible background page. A good value is large
     * enough to reduce the number of repaints that is caused for auto-
     * translation, which depends on this value, and small enough to give
     * a small empty buffer around the graph.
     */
    scrollTileSize: mxRectangle;

**Comment by tbouffard** [comment]
Hi, where does this come from?
It is not available in https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/src/js/view/mxGraph.js

**Comment by hungtcs** [comment]
Duplicate of https://github.com/typed-mxgraph/typed-mxgraph/issues/62
