### ISSUE TITLE
Add the 'getPageLayout' property to the 'mxGraph' class

### ISSUE THREAD

**Issue by EfrenHerrera** [typed-mxgraph/typed-mxgraph#62]
/**
   * Returns a rectangle describing the position and count of the
   * background pages, where x and y are the position of the top,
   * left page and width and height are the vertical and horizontal
   * page count.
   */
  getPageLayout(): mxRectangle;

**Comment by hungtcs** [comment]
@EfrenHerrera  Is that what you mean? I didn't find the `getPageLayout` method anywhere else except here. The code here is in the examples folder and is just an example, not included in mxgraph itself.

https://github.com/jgraph/mxgraph/blob/ff141aab158417bd866e2dfebd06c61d40773cd2/javascript/examples/grapheditor/www/js/Graph.js#L2449

**Comment by hungtcs** [comment]
@tbouffard Thanks for the correction.
