### ISSUE TITLE
Type generation

### ISSUE THREAD

**Issue by peteruhnak** [typed-mxgraph/typed-mxgraph#7]
Hi!

Is this project generated from mxGraph docs using something?

I am seeing that optional properties are often not marked as such:

e.g.

https://github.com/typed-mxgraph/typed-mxgraph/blob/master/view/mxGraph.d.ts#L1745-L1748

which presumably should be

```
removeCells(cells: mxCell[], includeEdges?: boolean): mxCell[];
```

Should I submit a manual fix for such things, or should I fix the type generator, if there's such a thing?

**Comment by hungtcs** [comment]
Hello @peteruhnak, thanks for you feedback. 
This project do not using generater, all types are manually inferred from source code or docs. 
If you find any errors, you can submit a PR or report bugs via issues, I will deal with these issues regularly.

**Comment by tbouffard** [comment]
@peteruhnak in addition to already provided explanations
The mxgraph lib is almost fully covered by types in this project.

The issues you may encounter are
- API changes in recent mxgraph have not been reported. We haven't currently decided how we will manage this, so for now, they are updated when user detect issues
- function arguments types or 'mandatoriness' may not be accurate as in the example you mention: even by reading the JS code, it is sometimes hard to figure out what is the correct type. Historically, we try to avoid `any` and use `optional` when we don't know. We expect user to provide feedbacks as you do to notice potential issue.

We will probably document the process in the future to make it clearer.
